version: '3.5'

services:

  mysql-db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "./data:/var/lib/mysql"
